name = "GAPLib"
uuid = "0ddd3828-f1ca-483d-8e76-89fb3a233c64"
authors = ["Rafael Martinelli"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
