name: Documenter
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  Documenter:
    permissions:
      contents: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # docs:
    # name: Documentation
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: julia-actions/setup-julia@v1
    #     with:
    #       version: '1'
    #   - run: |
    #       julia --project=docs -e '
    #         using Pkg
    #         Pkg.develop(PackageSpec(path=pwd()))
    #         Pkg.instantiate()'
    #   - run: |
    #       julia --project=docs -e '
    #         using Documenter: DocMeta, doctest
    #         using AssignmentProblems
    #         DocMeta.setdocmeta!(AssignmentProblems, :DocTestSetup, :(using AssignmentProblems); recursive=true)
    #         doctest(AssignmentProblems)'
    #   - run: julia --project=docs docs/make.jl
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}